•prototype和__proto__的关系是什么
•meta viewport原理
•域名收敛是什么
•float和display：inline-block；的区别
•前端优化策略列举
•首屏、白屏时间如何计算
•闭包
•作用域链
•ajax如何实现、readyState五中状态的含义
•jsonp如何实现
•怎么处理跨域
•restful的method解释
•get和post的区别
•事件模型解释
事件模型: dom0级事件模型  dom2
•编写一个元素拖拽的插件
•编写一个contextmenu的插件
•编写web端cookie的设置和获取方法
•兼容ie６的水平垂直居中
•兼容ie的事件封装
•h5和原生android的优缺点
•编写h5需要注意什么
•xss和crsf的原理以及怎么预防
•css优先级
•如何实现点击radio的文字描述控制radio的状态（通过label实现）
•delegate如何实现
•angularjs
•angular的directive怎么写
•angular的脏检查（双向绑定）是如何实现的
•依赖注入如何实现
•scope如何实现
•Sparse模块如何实现（主要自己写了一个类似的库）
•react
•react在setState后发生了什么（直接说了setState源码）
•flux解释
•对react有什么了解（直接说了react中虚拟dom内部表示，mount过程源码和同步过程源码）
•node
•Buffer模块是干什么的
•Stream是什么，使用的两种模式
•http模块如何将异步处理方式实现成同步处理方式，具体解析请参考http模块如何将异步•处理转成同步处理
•utf8和gbk的区别
•知道页面上某个点的坐标，如何获取该坐标上的所有元素
•angular、react和jQuery适合哪些应用场景（建议查看各个框架产生背景）
•7点15分小于180度的夹角是多少
•大数相加
•给５升和６升的水杯如何倒出３升的水
•一班喜欢足球的人60%，喜欢排球的70%，喜欢篮球的80%，求喜欢足球和排球的占多少
•前端异常监测如何实现
•直播点赞按钮的冒泡功能如何实现
•js的uglify如何实现
•项目架构、如何带人
•前端工程化方面做了哪些东西